export class WebAppDataView {
 items: Array<WebAppDataViewItem> = new Array<WebAppDataViewItem>();
 itemsCount: number;
}

export class WebAppDataViewItem {
  recId: number;
  rowId: string;
  profileTypeId: number | null;
  holidayYear: number | null;
  weekNumber: number | null;
  keyPeriodName: string;
  regionName: string;
  parkName: string;
  parkId: number | null;
  accommId: number | null;
  accommName: string;
  accommTypeName: string;
  accommBeds: number | null;
  accommPax: number | null;
  unitGradeName: string;
  arrivalDateRevised: Date | string | null;
  responsibleRevenueManager: string;
  parkPrioritisationScore: number | null;
  parkNightsTargetDeviation: number | null;
  parkWeekOccupancy: number | null;
  unitGradePrioritisationScore: number | null;
  unitFradeNightsTargetDeviation: number | null;
  unitGradeWeekOccupancy: number | null;
  unitGradeRecencyOfLastSale: number | null;
  accommWeekOccupancy: number | null;

  friRackRate: number | null;
  friCurrentFitPrice: number | null;
  friCurrentStandardDiscount: number | null;
  friCurrentEnhancedDiscount: number | null;
  friCurrentCampaignDiscount: number | null;
  friCurrentAdditionalDiscount: number | null;
  friCurrentSellingPrice: number | null;
  friRecommendedFitPrice: number | null;
  friNewFitPrice: number | null;
  friRecommendedDiscount: number | null;
  friNewDiscount: number | null;
  friNewEnhancedDiscount: number | null;
  friNewCampaignDiscount: number | null;
  friNewAdditionalDiscount: number | null;
  friRecommendedSellingPrice: number | null;
  friNewSellingPrice: number | null;
  friSellingPriceChange: number | null;
  friPriceChangeStatus: number | null;
  friBookedUnitsTotal: number | null;
  friBookedUnitsVarianceYoy: number | null;
  friBookedUnitsYoyAbvVariance: number | null;
  friCurrentUnitsAvailable: number | null;
  friLastPriceChange: number | null;
  friDaysSinceLastChange: number | null;
  friBookingsSinceLastChange: number | null;
  friMinimumPrice: number | null;
  friUpdatedBy: string;

  satRackRate: number | null;
  satCurrentFitPrice: number | null;
  satCurrentStandardDiscount: number | null;
  satCurrentEnhancedDiscount: number | null;
  satCurrentCampaignDiscount: number | null;
  satCurrentAdditionalDiscount: number | null;
  satCurrentSellingPrice: number | null;
  satRecommendedFitPrice: number | null;
  satNewFitPrice: number | null;
  satRecommendedDiscount: number | null;
  satNewDiscount: number | null;
  satNewEnhancedDiscount: number | null;
  satNewCampaignDiscount: number | null;
  satNewAdditionalDiscount: number | null;
  satRecommendedSellingPrice: number | null;
  satNewSellingPrice: number | null;
  satSellingPriceChange: number | null;
  satPriceChangeStatus: number | null;
  satBookedUnitsTotal: number | null;
  satBookedUnitsVarianceYoy: number | null;
  satBookedUnitsYoyAbvVariance: number | null;
  satCurrentUnitsAvailable: number | null;
  satLastPriceChange: number | null;
  satDaysSinceLastChange: number | null;
  satBookingsSinceLastChange: number | null;
  satMinimumPrice: number | null;
  satUpdatedBy: string;

  monRackRate: number | null;
  monCurrentFitPrice: number | null;
  monCurrentStandardDiscount: number | null;
  monCurrentEnhancedDiscount: number | null;
  monCurrentCampaignDiscount: number | null;
  monCurrentAdditionalDiscount: number | null;
  monCurrentSellingPrice: number | null;
  monRecommendedFitPrice: number | null;
  monNewFitPrice: number | null;
  monRecommendedDiscount: number | null;
  monNewDiscount: number | null;
  monNewEnhancedDiscount: number | null;
  monNewCampaignDiscount: number | null;
  monNewAdditionalDiscount: number | null;
  monRecommendedSellingPrice: number | null;
  monNewSellingPrice: number | null;
  monSellingPriceChange: number | null;
  monPriceChangeStatus: number | null;
  monBookedUnitsTotal: number | null;
  monBookedUnitsVarianceYoy: number | null;
  monBookedUnitsYoyAbvVariance: number | null;
  monCurrentUnitsAvailable: number | null;
  monLastPriceChange: number | null;
  monDaysSinceLastChange: number | null;
  monBookingsSinceLastChange: number | null;
  monMinimumPrice: number | null;
  monUpdatedBy: string;

  allNotAproved: boolean;
}
